### ISSUE TITLE
The order of fields on obstetric history on No. of previous pregnancy.

### ISSUE THREAD

**Issue by gladysyabs** [BlueCodeSystems/who-anc#243]
Get the Gestational age? 

Then find out if this was a live birth. If it was a live birth showing the following fields.

- Live birth?

options Yes/No

 If Yes show the following field

- Sex of infant?

 options: Male /Female

- Mode of delivery

option: Natural/C-Section.

Then show the Birth weight in grams

- Birth Weight

Then show the field 

Any  complications in child birth?
options Yes/No

Puerperium
options Normal/Abnormal

Date of Delivery / Determination.

Estimated date of delivery/ Determination

- If No to Live birth  show the following field

Still birth ?
options Yes/No

If Yes then show the following

 If Yes show the following field

- Sex of infant?

 options: Male /Female/Unknown

- Mode of delivery

option: Natural/C-Section.

Then show the Birth weight in grams

- Birth Weight

Then show the field 

Any  complications in child birth?
options Yes/No

Puerperium
options Normal/Abnormal

Date of Delivery / Determination.

Estimated date of delivery/ Determination

If No to stillbirth show the following

Miscarriage/Abortion?
options: Yes/No

If Yes show the following fields

Date of Delivery / Determination.

Estimated date of delivery/ Determination

**Comment by tobiasmakai** [comment]
The field should take in month and date only

**Comment by tobiasmakai** [comment]
Infact, because there was a requirement to add a field named "Estimated Year of Delivery" we can leave this field as is just name it " "Date of Delivery/Termination" if user does not remember the date that is when they can fill in the field "Estimated Date of Delivery". The last field should only appear if a some check box (can be named "Cannot remember") is checked. The two fields can not appear at the same time. See how the checkbox below date of birth on the registration form behaves.
